CREATE DATABASE haebeop;

USE haebeop;

CREATE TABLE test(
	num INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(100) NOT NULL);

INSERT INTO test VALUES (DEFAULT, '테스트제목1');
INSERT INTO test VALUES (DEFAULT, '테스트제목2');
INSERT INTO test VALUES (DEFAULT, '테스트제목3');
INSERT INTO test VALUES (DEFAULT, '테스트제목4');
INSERT INTO test VALUES (DEFAULT, '테스트제목5');

SELECT * from test;

COMMIT;

CREATE TABLE emp(
	emp_no INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(50)
);

INSERT INTO emp VALUES(DEFAULT, 'shin');